import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { ADMIN_PORTAL_SECTION_KEYS, IMPLEMENTED_ADMIN_RUNTIME_DESTINATION_KEYS } from "../src/application/admin/portal-navigation.ts";
function read(relativePath){return readFile(new URL(`../${relativePath}`,import.meta.url),"utf8");}

test("all nineteen canonical admin sections have protected top-level runtimes",()=>{assert.equal(ADMIN_PORTAL_SECTION_KEYS.length,19);for(const key of ADMIN_PORTAL_SECTION_KEYS)assert.ok(IMPLEMENTED_ADMIN_RUNTIME_DESTINATION_KEYS.includes(key));assert.ok(IMPLEMENTED_ADMIN_RUNTIME_DESTINATION_KEYS.includes("organization-claims"));});
test("data promotion is market-agnostic and does not make Hampton Roads an admin boundary",async()=>{const domain=await read("src/application/admin/domain-operations.ts");const runtime=await read("src/infrastructure/admin/domain-operations-runtime.ts");const page=await read("apps/admin/app/admin/data-promotion/page.tsx");assert.match(domain,/Source Packages/);assert.match(runtime,/marketKey/);assert.match(runtime,/providerSeedPromotionCandidates/);assert.match(runtime,/providerSeedPromotionApprovals/);assert.match(runtime,/Separate from promotion/);assert.doesNotMatch(page,/hampton-roads/i);assert.doesNotMatch(runtime,/marketKey\s*===\s*["']hampton-roads/i);});
test("authority, verification and credibility remain distinct",async()=>{const domain=await read("src/application/admin/domain-operations.ts");assert.match(domain,/Authority answers who may represent an organization/);assert.match(domain,/Verification answers what RFxchange has independently established/);assert.match(domain,/hidden score/);assert.doesNotMatch(domain,/credibilityScore|trustScore|rankScore/);});
test("User Access 360 consumes the existing typed projection",async()=>{const page=await read("apps/admin/app/admin/users/[userId]/page.tsx");assert.match(page,/buildUserAccess360/);assert.match(page,/FirestoreUserIdentityRepository/);assert.match(page,/FirestoreOrganizationMembershipRepository/);assert.match(page,/user\.profile\.read/);assert.match(page,/user\.access\.read/);});
