import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

import { ADMIN_PORTAL_SECTION_KEYS, IMPLEMENTED_ADMIN_RUNTIME_DESTINATION_KEYS } from "../src/application/admin/portal-navigation.ts";
function read(relativePath){return readFile(new URL(`../${relativePath}`,import.meta.url),"utf8");}

test("the administrative product authority defines an attention-first restrained control plane",async()=>{const authority=await read("docs/design/ADMIN_PORTAL_PRODUCT_AUTHORITY.md");const context=await read("docs/context/ADMINISTRATION.md");assert.match(authority,/attention-first, scope-visible operating workspace/i);assert.match(authority,/Less container chrome/);assert.match(authority,/Human language over implementation language/);assert.match(authority,/only destinations with a truthful implemented runtime/i);assert.match(authority,/authority, verification, provider status, commerce, and credibility remain visibly separate/i);assert.match(context,/ADMIN_PORTAL_PRODUCT_AUTHORITY\.md/);});

test("all nineteen canonical admin sections now have protected top-level runtimes",()=>{assert.equal(ADMIN_PORTAL_SECTION_KEYS.length,19);for(const key of ADMIN_PORTAL_SECTION_KEYS)assert.ok(IMPLEMENTED_ADMIN_RUNTIME_DESTINATION_KEYS.includes(key));assert.ok(IMPLEMENTED_ADMIN_RUNTIME_DESTINATION_KEYS.includes("organization-claims"),"legacy adjudication remains supporting-only");});

test("live administrative surfaces share one product shell",async()=>{for(const path of ["app/admin/organizations/page.tsx","app/admin/users/page.tsx","app/admin/claims-verification/page.tsx","app/admin/geographies/page.tsx","app/admin/institutions/page.tsx","app/admin/rfx/page.tsx","app/admin/referrals-teaming/page.tsx","app/admin/credibility/page.tsx","app/admin/trust-safety/page.tsx","app/admin/commerce/page.tsx","app/admin/support/page.tsx","app/admin/communications/page.tsx","app/admin/analytics/page.tsx","app/admin/configuration/page.tsx","app/admin/system/page.tsx","app/admin/audit-security/page.tsx","app/admin/data-promotion/page.tsx"]){assert.match(await read(path),/AdminDomainPage/);}for(const path of ["app/admin/organization-claims/page.tsx","app/admin/resource-providers/page.tsx","app/admin/organizations/[organizationId]/page.tsx","app/admin/overview/page.tsx","app/admin/work-queues/page.tsx"]){assert.match(await read(path),/AdminPortalShell/);}});

test("shared remaining-sequence workspace follows RFxchange brand and mobile rules",async()=>{const source=await read("src/components/admin/AdminDomainWorkspace.tsx");const styles=await read("src/components/admin/AdminDomainWorkspace.module.css");assert.match(source,/Needs attention/);assert.match(source,/Open authoritative record/);assert.doesNotMatch(source,/<table/);assert.match(styles,/#f5f0e5/i);assert.match(styles,/#111210/i);assert.match(styles,/#705119/i);assert.match(styles,/min-height:44px/);assert.match(styles,/@media\(max-width:820px\)/);assert.match(styles,/prefers-reduced-motion/);assert.doesNotMatch(styles,/overflow-x:\s*auto/);});

test("data promotion is geography-agnostic and Hampton Roads is not an admin route boundary",async()=>{const domain=await read("src/application/admin/domain-operations.ts");const runtime=await read("src/infrastructure/admin/domain-operations-runtime.ts");const page=await read("app/admin/data-promotion/page.tsx");assert.match(domain,/Source Packages/);assert.match(runtime,/marketKey/);assert.match(runtime,/providerSeedPromotionCandidates/);assert.match(runtime,/providerSeedPromotionApprovals/);assert.match(runtime,/Publication.*Separate from promotion/);assert.doesNotMatch(page,/hampton-roads/i);assert.doesNotMatch(runtime,/marketKey\s*===\s*["']hampton-roads/i);});

test("authority and verification remain distinct and credibility does not create hidden scoring",async()=>{const domain=await read("src/application/admin/domain-operations.ts");assert.match(domain,/Authority answers who may represent an organization/);assert.match(domain,/Verification answers what RFxchange has independently established/);assert.match(domain,/without converting self-report, evidence or endorsements into a hidden score/);assert.doesNotMatch(domain,/credibilityScore|trustScore|rankScore/);});

test("User Access 360 consumes the existing typed projection",async()=>{const page=await read("app/admin/users/[userId]/page.tsx");assert.match(page,/buildUserAccess360/);assert.match(page,/FirestoreUserIdentityRepository/);assert.match(page,/FirestoreOrganizationMembershipRepository/);assert.match(page,/user\.profile\.read/);assert.match(page,/user\.access\.read/);});

test("operating core remains intact",async()=>{const runtime=await read("src/infrastructure/admin/operating-core-runtime.ts");const queue=await read("src/components/admin/AdminWorkQueueWorkspace.tsx");const casePage=await read("app/admin/cases/[caseId]/page.tsx");const caseApi=await read("app/api/admin/cases/[caseId]/transition/route.ts");assert.match(runtime,/authorityWithActiveGlobalGrants/);assert.match(queue,/Open full case/);assert.match(casePage,/CASE:/);assert.match(caseApi,/expectedStatus/);});
