import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {LENSES,validLens,routeState,routeQuery,queryKey,snapOffsets,chooseSnap,coordinate,safeVideo,MemoryCache} from '../public/model.mjs';

test('four lenses and AccelPO remains a separate destination',()=>{assert.deepEqual(Object.keys(LENSES),['rfx','resources','intelligence','capabilities']);assert.equal(validLens('accelpo'),'rfx');assert.equal(validLens('__proto__'),'rfx');});
test('URL state round-trips without credentials',()=>{const s={lens:'intelligence',q:'K9 & security',selected:'organization:abc',deadline:'',watched:false,availability:''};assert.deepEqual(routeState(routeQuery(s)),s);assert.equal(routeState('?q='+ 'x'.repeat(999)).q.length,120);assert.equal(queryKey(s),queryKey({...s,selected:'organization:other'}));});
test('valid geography does not invent points',()=>{assert.deepEqual(coordinate([-76.4,36.9]),[-76.4,36.9]);for(const x of [null,[200,90],[0,91],[NaN,0],['1',2],[1,2,3]])assert.equal(coordinate(x),null);});
test('snap offsets fit short and tall viewports',()=>{for(const height of [120,320,550,850]){const o=snapOffsets(height,height+200);assert.equal(o.expanded,0);assert.ok(o.partial>=0&&o.partial<=o.peek);assert.ok(o.peek<=height);assert.equal(chooseSnap(o.peek,0,o),'peek');assert.equal(chooseSnap(0,0,o),'expanded');}});
test('snap velocity moves in the gesture direction',()=>{const o=snapOffsets(600,800);assert.equal(chooseSnap(o.partial,-1,o),'expanded');assert.equal(chooseSnap(o.partial,2,o),'peek');});
test('cache bounded, expiring, and explicitly cleared at session changes',()=>{let now=0;const cache=new MemoryCache(100,2,()=>now);cache.set('u1:org1','one');cache.set('u1:org2','two');assert.equal(cache.get('u2:org1'),null);cache.set('u1:org3','three');assert.equal(cache.get('u1:org1'),null);now=101;assert.equal(cache.get('u1:org2'),null);cache.clear();assert.equal(cache.get('u1:org3'),null);});
test('media is bounded to 30 seconds and approved sources',()=>{const good={kind:'linked',url:'https://www.youtube-nocookie.com/embed/abcdefghijk',durationSeconds:30};assert.equal(safeVideo(good),good);for(const url of ['https://attacker.test/embed/abcdefghijk','javascript:alert(1)','https://www.youtube-nocookie.com:444/embed/abcdefghijk','https://www.youtube-nocookie.com/embed/abcdefghijk?other=true'])assert.equal(safeVideo({...good,url}),null);for(const durationSeconds of [0,-1,30.001,NaN,Infinity])assert.equal(safeVideo({...good,durationSeconds}),null);assert.ok(safeVideo({kind:'uploaded',url:'/api/exchange/media?organization=abc&part=video',durationSeconds:12}));assert.equal(safeVideo({kind:'uploaded',url:'https://external.test/movie.mp4',durationSeconds:12}),null);});
test('no parallel provider system or direct canonical Firestore access in browser',async()=>{const client=await readFile(new URL('../public/exchange.mjs',import.meta.url),'utf8');assert.doesNotMatch(client,/firebase-firestore|localStorage|sessionStorage|getSignedUrl|TELNYX_API_KEY|STRIPE_SECRET_KEY|innerHTML/);assert.match(client,/requestAnimationFrame/);assert.match(client,/pointercancel/);assert.match(client,/lostpointercapture/);assert.match(client,/clearPrivateState/);const auth=await readFile(new URL('../app/api/auth/session/route.ts',import.meta.url),'utf8');assert.match(auth,/@\/app\/api\/auth\/session\/route/);});
test('service worker never caches API/auth/private media or navigation',async()=>{const worker=await readFile(new URL('../public/sw.js',import.meta.url),'utf8');assert.match(worker,/ASSETS/);assert.match(worker,/includes/);assert.doesNotMatch(worker,/\/api\/|runtime-config\.json|skipWaiting/);});
